apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: catalog
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingestion
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: ingestion
---
apiVersion: v1
kind: Namespace
metadata:
  name: processing
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: processing
---
apiVersion: v1
kind: Namespace
metadata:
  name: query
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: query
---
apiVersion: v1
kind: Namespace
metadata:
  name: bi
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: bi
---
apiVersion: v1
kind: Namespace
metadata:
  name: orchestration
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: orchestration
---
apiVersion: v1
kind: Namespace
metadata:
  name: maintenance
  labels:
    app.kubernetes.io/part-of: open-iceberg-stack
    app.kubernetes.io/component: maintenance
